const routesConfig = [
  {
    id: 'dashboards',
    title: 'Home',
    messageId: 'sidebar.app.home',
    type: 'item',
    icon: 'dashboard',
    url: '/dashboards/analytics',
    // children: [
    //   {
    //     id: 'healthCare',
    //     title: 'Health Care',
    //     messageId: 'sidebar.healthCare',
    //     type: 'item',
    //     url: '/dashboards/health-care',
    //   },
    //   {
    //     id: 'e-commerce',
    //     title: 'E-Commerce',
    //     messageId: 'sidebar.app.dashboard.eCommerce',
    //     type: 'item',
    //     url: '/dashboards/e-commerce',
    //   },
    //   {
    //     id: 'academy',
    //     title: 'Academy',
    //     messageId: 'sidebar.app.dashboard.academy',
    //     type: 'item',
    //     url: '/dashboards/academy',
    //   },
    //   {
    //     id: 'analytics',
    //     title: 'Analytics',
    //     messageId: 'sidebar.app.dashboard.analytics',
    //     type: 'item',
    //     url: '/dashboards/analytics',
    //   },
    //   {
    //     id: 'crm',
    //     title: 'CRM',
    //     messageId: 'sidebar.app.dashboard.crm',
    //     type: 'item',
    //     url: '/dashboards/crm',
    //   },
    //   {
    //     id: 'crypto',
    //     title: 'Crypto',
    //     messageId: 'sidebar.app.dashboard.crypto',
    //     type: 'item',
    //     url: '/dashboards/crypto',
    //   },
    // ],
  },
  {
    id: 'pages',
    title: 'Pages',
    messageId: 'sidebar.app.pages',
    type: 'collapse',
    icon: 'insert_chart',
    url: '/pages/',
  },
  {
    id: 'apis',
    title: 'Apis',
    messageId: 'sidebar.app.apis',
    type: 'item',
    icon: 'storage',
    url: '/apis',
  },
  {
    id: 'routes',
    title: 'Routes',
    messageId: 'sidebar.app.routes',
    type: 'item',
    icon: 'swap_vert',
    url: '/routes',
  },
  {
    id: 'sitemap',
    title: 'SiteMap',
    messageId: 'sidebar.app.sitemap',
    type: 'item',
    icon: 'account_tree',
    url: '/sitemap',
  },
  {
    id: 'widgets',
    title: 'Widgets',
    messageId: 'sidebar.app.widgets',
    type: 'item',
    icon: 'widgets',
    url: '/dashboards/widgets',
  },

  {
    id: 'amp',
    title: 'Amp Pages & Stories',
    messageId: 'sidebar.app.ampPages',
    type: 'item',
    icon: 'amp_stories',
    url: '/dashboards/amp',
  },
  {
    id: 'emailers',
    title: 'Emailers',
    messageId: 'sidebar.app.emailers',
    type: 'item',
    icon: 'mail-outline',
    url: '/emailers',
  },
  {
    id: 'analytics',
    title: 'Analytics',
    messageId: 'sidebar.app.analytics',
    type: 'item',
    icon: 'timeline',
    url: '/analytics',
  },
  {
    id: 'buildDeploy',
    title: 'Build & Deploy',
    messageId: 'sidebar.app.buildDeploy',
    type: 'item',
    icon: 'build',
    url: '/deploy',
  },
  {
    id: 'settings',
    title: 'Settings',
    messageId: 'sidebar.app.settings',
    type: 'item',
    icon: 'settings',
    url: '/settings',
  },
];
export default routesConfig;
